### ISSUE TITLE
Database explorer integration

### ISSUE THREAD

**Issue by ViCt0r99** [RomainBes/DataVizChallenge#3]
Hi @RomainBes,

I'm using your code to build a [visualization library](https://github.com/LowerSilesians/brightway) for Brightway. I may have some issues with understanding parts of your code and I want to keep the conversation with you until I'm confident that your code is properly integrated in our library if you'll have the time for that. First few things related to your prepared library:
- I'd be glad if you have some time to check whether the logic that you implemented is intact, because we had to make few changes to your code base: https://github.com/LowerSilesians/brightway/tree/main/bw_visualization/database_explorer,
- Could you provide a meaningful example for documentation and manual testing with US EEIO database?

**Comment by RomainBes** [comment]
Hi @ViCt0r99, I'll do my best to have a look in the coming days. If it can be useful for you, we can exchange in a short call as well, maybe I can clarify what I did.

**Comment by HamedAkhavan** [comment]
Hi @RomainBes ,
I'm working with Wiktor on the project. we want to write a test for your code but with _USEEIO-1.1-noproducts_ database. we're currently having problems with defining correct inputs to the tests since our reference (your test) is using another database. any help would be very appreciated?
code is [here](https://github.com/LowerSilesians/brightway/blob/feature/BRIG-4/add-tests/tests/database_explorer/utils.py)
thanks

**Comment by RomainBes** [comment]
Hi @ViCt0r99 and @HamedAkhavan,

I had a look at the code and the logic seems respected. 
I tried to run the code using the US EEIO database however most, if not all, functions failed as databases are relatively different: they do not have the same field for instance. Or when you choose a random activity of the EEIO database, the dataset does not have any associated inventory (act = bd.Database('US EEIO').random(), act.exchanges().to_dataframe() is an empty whereas it is not the case with ecoinvent database. 
It is hard for me to know what point of the code you don't understand. I think the best would be exchange via a call to discuss what we did.

**Comment by RomainBes** [comment]
Playing with the EEIO database, I think I understood some issues related to the various type of dataset.
You can find at this link a new notebook and library to be used for the USEEIO data: http://e.pc.cd/jNxotalK

Some features previously developed using the ecoinvent database lose their interest, but some remains useful, let's meet this thursday to clarify that.
